### ISSUE TITLE
Crash when adding a new contact

### ISSUE THREAD

**Issue by rqcy** [SilenceIM/Silence#409]
Silence crashes when I try to add a new contact to the list by clicking the blue round icon with a pen and start to type _i_ in the contact search field (Enter name or number).

```
05-25 23:40:50.522 21351 21381 E AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
05-25 23:40:50.522 21351 21381 E AndroidRuntime: Process: org.smssecure.smssecure, PID: 21351
05-25 23:40:50.522 21351 21381 E AndroidRuntime: java.lang.RuntimeException: An error occurred while executing doInBackground()
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at android.os.AsyncTask$3.done(AsyncTask.java:309)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at java.lang.Thread.run(Thread.java:818)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'java.lang.String org.smssecure.smssecure.recipients.Recipient.getNumber()' on a null object reference
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at org.smssecure.smssecure.crypto.SessionUtil.hasSession(SessionUtil.java:14)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at org.smssecure.smssecure.components.AvatarImageView$BadgeResolutionTask.doInBackground(AvatarImageView.java:104)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at org.smssecure.smssecure.components.AvatarImageView$BadgeResolutionTask.doInBackground(AvatarImageView.java:93)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at android.os.AsyncTask$2.call(AsyncTask.java:295)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
05-25 23:40:50.522 21351 21381 E AndroidRuntime: 	... 4 more
05-25 23:40:50.528  2225  2783 W ActivityManager:   Force finishing activity org.smssecure.smssecure/.NewConversationActivity
```

**Comment by johanw666** [comment]
Related to https://github.com/WhisperSystems/Signal-Android/issues/5454 ?

**Comment by rqcy** [comment]
2016-05-26 10:09 +0200, johanw666 <notifications@github.com>:

> Related to https://github.com/WhisperSystems/Signal-Android/issues/5454 ?

Upgrading CM to the newest nightling didn't help.

I found that the offending contact had a comma (,) as a phone number.  I
think that by creating such contact, you can reproduce the crash.
