### ISSUE TITLE
"Unfortunately, Silence has stopped." at each access to Silence

### ISSUE THREAD

**Issue by FilLupin** [SilenceIM/Silence#594]
Hello,
I recently installed Silence 0.16.3 unstable (202). I configured a passphrase and send and receive several sms and mms.

### Bug description
Yesterday, I used Silence since one week when I noticed I received 3 sms. When trying to read them, I entered my passphrase and then, Silence crashed with message: "Unfortunately, Silence has stopped."
Since then, I can access to notifications if sms got received after Silence has been started, but Silence crashes each time I enter passphrase, after 0 to 1 second, just the time to watch the numbers of the sms sender.

After talking with one of the senders, he confirmed he tried to exchange keys to open a secure session.
However, he cannot stop secure session but just sending again new keys.
No sender sent attached picture or anything.

I do not have any recent export so I can not access to export function. I cannot uninstall and reinstall Silence, I understood it will remove all sms.
It seems linked to #555 and 
### How to reproduce
- when contact opened a secure session, open silence
- enter passphrase
- watch silence crash

### Device info
- Device: samsung GT-I9300
- Android version: 6.0.1
- Silence version: Silence 0.16.3-unstable
- Internal memory used : 73.04 Mb

### Link to debug log
Here is the log I got qith adb logcat after opening Silence, entering passphrase, and crashing Silence:

> 07-10 17:53:04.412 12282 12447 D lights  : set_light_buttons: 1
> 07-10 17:53:04.697 14405 14405 W KeyCachingService: onCreate()
> 07-10 17:53:04.697 14405 14405 W KeyCachingService: onStartCommand, null
> 07-10 17:53:04.697 14405 14405 W KeyCachingService: foregrounding KCS
> 07-10 17:53:04.717 14405 14405 W service : Broadcasting new secret...
> 07-10 17:53:04.742 12282 12944 I ActivityManager: START u0 {act=android.intent.action.MAIN cat=[android.intent.category.LAUNCHER] flg=0x10200000 cmp=org.smssecure.smssecure/.RoutingActivity bnds=[164,1134][298,1286] (has extras)} from uid 10064 on display 0
> 07-10 17:53:04.747 12847 12847 I LatinIME: Starting input. Cursor position = 8,8
> 07-10 17:53:04.787 14405 14405 W PassphraseRequiredActionBarActivity: onCreate(null)
> 07-10 17:53:04.787 14405 14405 W PassphraseRequiredActionBarActivity: routeApplicationState(), state: 0
> 07-10 17:53:04.792 14405 14405 W PassphraseRequiredActionBarActivity: initializeClearKeyReceiver()
> 07-10 17:53:04.792 14405 14405 W SubscriptionManagerCompat: from()
> 07-10 17:53:04.872 14405 14420 W art     : Long monitor contention event with owner method=void org.smssecure.smssecure.database.DatabaseFactory.<init>(android.content.Context) from DatabaseFactory.java:172 waiters=2 for 116ms
> 07-10 17:53:04.927 14405 14421 W SilenceSessionStore: SilenceSessionStore for subscription ID 1
> 07-10 17:53:04.937 14405 14420 W PublicKey: PublicKey Length: 36
> 07-10 17:53:04.942 14405 14405 W PassphraseRequiredActionBarActivity: onResume()
> 07-10 17:53:04.977 14405 14420 W SilenceSessionStore: SilenceSessionStore for subscription ID 1
> 07-10 17:53:05.002 14405 14421 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:05.032 14405 14405 W KeyCachingService: onStartCommand, org.smssecure.smssecure.service.action.ACTIVITY_START_EVENT
> 07-10 17:53:05.032 14405 14405 W KeyCachingService: Incrementing activity count...
> 07-10 17:53:05.137 14405 14442 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:05.137 14405 14420 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:05.152 14405 14442 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:05.242 14405 14423 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:05.242 14405 14422 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:05.247 14405 14439 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:05.667 14405 14405 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
> 07-10 17:53:05.667 14405 14405 I Choreographer: Skipped 33 frames!  The application may be doing too much work on its main thread.
> 07-10 17:53:05.677 12847 12847 W RichInputConnection: Slow InputConnection: GET_TEXT_BEFORE_CURSOR took 643 ms.
> 07-10 17:53:05.767 12282 12315 I ActivityManager: Displayed org.smssecure.smssecure/.RoutingActivity: +996ms
> 07-10 17:53:05.782 14405 14405 W IInputConnectionWrapper: getSelectedText on inactive InputConnection
> 07-10 17:53:06.077 14405 14405 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
> 07-10 17:53:06.082 12847 12847 E RichInputConnection: Unable to connect to the editor to retrieve text.
> 07-10 17:53:06.082 12847 12847 W RichInputConnection: Unable to connect to the editor. Setting caps mode without knowing text.
> 07-10 17:53:06.147 14405 14405 W IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
> 07-10 17:53:06.172 12847 12847 E RichInputConnection: Unable to connect to the editor to retrieve text.
> 07-10 17:53:06.172 12847 12847 W RichInputConnection: Unable to connect to the editor. Setting caps mode without knowing text.
> 07-10 17:53:06.177 14405 14405 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
> 07-10 17:53:06.192 14405 14405 W IInputConnectionWrapper: finishComposingText on inactive InputConnection
> 07-10 17:53:06.302 14405 14421 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:06.307 14405 14420 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:06.307 14405 14423 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:06.307 14405 14422 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:06.322 14405 14442 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:06.327 14405 14439 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:06.332 14405 14420 W SilenceSessionStore: No existing session information found.
> 07-10 17:53:06.347 14405 14423 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:06.352 14405 14421 W SilenceSessionStore: No existing session information found.
> 07-10 17:53:06.352 14405 14422 W RecipientPreferenceDatabase: Muted until: 0
> 07-10 17:53:06.357 14405 14421 W JobConsumer: java.lang.IllegalArgumentException: Null values!
> 07-10 17:53:06.357 14405 14421 W JobConsumer: 	at org.whispersystems.libsignal.ratchet.SymmetricSignalProtocolParameters.<init>(SymmetricSignalProtocolParameters.java:37)
> 07-10 17:53:06.357 14405 14421 W JobConsumer: 	at org.whispersystems.libsignal.ratchet.SymmetricSignalProtocolParameters$Builder.create(SymmetricSignalProtocolParameters.java:109)
> 07-10 17:53:06.357 14405 14421 W JobConsumer: 	at org.smssecure.smssecure.crypto.SessionBuilder.processInitiate(SessionBuilder.java:255)
> 07-10 17:53:06.357 14405 14421 W JobConsumer: 	at org.smssecure.smssecure.crypto.SessionBuilder.process(SessionBuilder.java:220)
> 07-10 17:53:06.357 14405 14421 W JobConsumer: 	at org.smssecure.smssecure.crypto.SmsCipher.process(SmsCipher.java:114)
> 07-10 17:53:06.357 14405 14421 W JobConsumer: 	at org.smssecure.smssecure.jobs.SmsDecryptJob.handleKeyExchangeMessage(SmsDecryptJob.java:171)
> 07-10 17:53:06.357 14405 14421 W JobConsumer: 	at org.smssecure.smssecure.jobs.SmsDecryptJob.onRun(SmsDecryptJob.java:93)
> 07-10 17:53:06.357 14405 14421 W JobConsumer: 	at org.smssecure.smssecure.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
> 07-10 17:53:06.357 14405 14421 W JobConsumer: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
> 07-10 17:53:06.357 14405 14421 W JobConsumer: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
> 07-10 17:53:06.362 14405 14420 W JobConsumer: java.lang.IllegalArgumentException: Null values!
> 07-10 17:53:06.362 14405 14420 W JobConsumer: 	at org.whispersystems.libsignal.ratchet.SymmetricSignalProtocolParameters.<init>(SymmetricSignalProtocolParameters.java:37)
> 07-10 17:53:06.362 14405 14420 W JobConsumer: 	at org.whispersystems.libsignal.ratchet.SymmetricSignalProtocolParameters$Builder.create(SymmetricSignalProtocolParameters.java:109)
> 07-10 17:53:06.362 14405 14420 W JobConsumer: 	at org.smssecure.smssecure.crypto.SessionBuilder.processInitiate(SessionBuilder.java:255)
> 07-10 17:53:06.362 14405 14420 W JobConsumer: 	at org.smssecure.smssecure.crypto.SessionBuilder.process(SessionBuilder.java:220)
> 07-10 17:53:06.362 14405 14420 W JobConsumer: 	at org.smssecure.smssecure.crypto.SmsCipher.process(SmsCipher.java:114)
> 07-10 17:53:06.362 14405 14420 W JobConsumer: 	at org.smssecure.smssecure.jobs.SmsDecryptJob.handleKeyExchangeMessage(SmsDecryptJob.java:171)
> 07-10 17:53:06.362 14405 14420 W JobConsumer: 	at org.smssecure.smssecure.jobs.SmsDecryptJob.onRun(SmsDecryptJob.java:93)
> 07-10 17:53:06.362 14405 14420 W JobConsumer: 	at org.smssecure.smssecure.jobs.MasterSecretJob.onRun(MasterSecretJob.java:18)
> 07-10 17:53:06.362 14405 14420 W JobConsumer: 	at org.whispersystems.jobqueue.JobConsumer.runJob(JobConsumer.java:76)
> 07-10 17:53:06.362 14405 14420 W JobConsumer: 	at org.whispersystems.jobqueue.JobConsumer.run(JobConsumer.java:46)
> 07-10 17:53:06.362 14405 14421 I Process : Sending signal. PID: 14405 SIG: 9
> 07-10 17:53:06.387 12282 12447 W InputDispatcher: channel '283b22f org.smssecure.smssecure/org.smssecure.smssecure.RoutingActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
> 07-10 17:53:06.387 12282 12447 E InputDispatcher: channel '283b22f org.smssecure.smssecure/org.smssecure.smssecure.RoutingActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
> 07-10 17:53:06.392 12282 12951 W InputDispatcher: Attempted to unregister already unregistered input channel '283b22f org.smssecure.smssecure/org.smssecure.smssecure.RoutingActivity (server)'
> 07-10 17:53:06.392 12282 12951 I WindowState: WIN DEATH: Window{283b22f u0 org.smssecure.smssecure/org.smssecure.smssecure.RoutingActivity}
> 07-10 17:53:06.407 12282 14268 I ActivityManager: Process org.smssecure.smssecure (pid 14405) has died
> 07-10 17:53:06.407 12282 14268 D ActivityManager: cleanUpApplicationRecord -- 14405
> 07-10 17:53:06.407 12282 14268 W ActivityManager: Scheduling restart of crashed service org.smssecure.smssecure/.service.KeyCachingService in 1000ms
> 07-10 17:53:06.412 12282 14268 W ActivityManager: Force removing ActivityRecord{8c2a0a4 u0 org.smssecure.smssecure/.RoutingActivity t885}: app died, no saved state
> 07-10 17:53:06.457 12282 12420 W InputMethodManagerService: Got RemoteException sending setActive(false) notification to pid 14405 uid 10064
> 07-10 17:53:07.437 12892 13138 W AudioFxService: self destructing, no sessions active and nothing to do.
> 07-10 17:53:11.187 12282 12397 D lights  : set_light_buttons: 2

**Comment by johanw666** [comment]
Unfortunately, "unstable" here really means unstable. Better to tick to 0.15.7 for the time being.

**Comment by FilLupin** [comment]
Thank you for your answer. Whatever, I hope it will help you to stabilize the code.
It seems the error is when exchanging keys, with the line::
  07-10 17:53:06.357 14405 14421 W JobConsumer: java.lang.IllegalArgumentException: Null values!

No problem for me, can I do this without loosing my SMS?
Do I need to backup some files?

**Comment by johanw666** [comment]
You need backup files, but since the format of the 0.15.7 database differs from the 0.16 version an encrypted backup won't work. If you have only text messages and no mms or group messages the plaintext backup should do. Better make both in case something fails. They are not made automatically so make them manually before deinstalling 0.16.

The tables could probably be manually converted with a sql tool but that requires some study.

**Comment by FilLupin** [comment]
I ma not sure I have an encrupted backup. I just configured a passphrase.

Since I cannot access to the app, how can I backup my sms? I have some backup from 1 month ago, but I would like to keep my sms received since. I can possibly loose MMS receveid since last backup if it is absolutly not possible to keep them.

**Comment by FilLupin** [comment]
I confirmed my backup seems not encrypted: I opened my old backup and I can read the sms.

However, I still do not know how to make a backup manually since I can not access to backup button.

**Comment by johanw666** [comment]
If you are rooted you can use Titanium Backup or copy the files in /data/data/org.smssecure/smssecure manually. If not, you can try to copy them with adb if you put the device in usb debug mode.

**Comment by FilLupin** [comment]
Thank you. I am root.
So to not avoid anything, I have to:
1. save /data/data/org.smssecure.smssecure directory
> adb root
> adb pull /data/data/org.smssecure.smssecure
2. uninstall silence
3. reinstall silence

If I understand well what you said, I will not loose anything doing this way since my sms are not encrypted. 
Am I correct?

**Comment by johanw666** [comment]
If you get those files, you can always restore them and return to the exact same situation you are in now. If you install 0.15.7, you could try to get the databases in that format by reversing the queries used to get the databases in 0.16 format. I would have to check the source to see what those exactly are.

**Comment by FilLupin** [comment]
OK, so I got the backup this way.
Thank you so much for such help! :)
However, I did not understand if this manual backup on 0.16 can be imported and used on 0.15 version...

**Comment by FilLupin** [comment]
I imagine it could be tested by : 
- exporting sms under silence 0.16 version
- uninstalling silence 0.16.xx version
- installing silence 0.15.xx version
- importing sms

**Comment by johanw666** [comment]
No, it can not be used on 0.15, that's why I wrote about reversing the sql queries that turn a 0.15 database in a 0.16 database.

**Comment by FilLupin** [comment]
OK, so I am not sure to see exactly what I need to reverse import/export operations.
This could you help me if the lines and concerned file are identified: could you help me with this? I do not know what this implies and I am not sure I will understand the formats used but I can try at least. 

Another way to test would be to uninstall 0.16: either the exchanged keys could be lost and solve my error or I could try to identify the place where the information of the exchange key is kept to reinitialize it.
This second way seems a lot easier to me. Do you think you can help me with identifying the place where is kept the state of exchanged keys?
Thank you.

**Comment by johanw666** [comment]
To brting a 0.16 database into a 0.15 state you would need to look in src/org/smssecure/smssecure/Database/DatabaseFactory.java in the method OnCreate(). There is a list of sql queries that gets executed if the database is in a certain state to update it, at some point 0.16 and 0.15 start to differ. You would have to compare those from the 0.16 and 0.15 source. Then the puzzle begins.

Of course, if you make a plaintext backup, uninstall 0.16 and reinstall 0.15 and set back the plaintext backup, you loose some things (identity keys and media messages) but it would be a much easier way. I would make an encrypted full backup as well anyway, just in case.

**Comment by FilLupin** [comment]
Thank you for the code localisation. 

It seems to make an encrypted full backup, I need to access to app, but I can not since as soon I enter passphrase, app crashes.
Do you think I could just manually backup some directory to save multumedia messages and push them back?

**Comment by johanw666** [comment]
Yes, that should be possible. If you manually do that and don't use a backup tool remember to also manually check and set the owner/group of the files. I think the crash would also return then, but it should be possible.

**Comment by FilLupin** [comment]
The biggest issue is then to reinitialize exchanged keys. Could you help me identify the place where is kept the state of exchanged keys?

**Comment by FilLupin** [comment]
Another question : if I get uninstall and reinstall 0.16, to avoid export issues, how to unset exchanged key?

**Comment by FilLupin** [comment]
Without answer, I tried to uninstall and reinstall Silence in another version, and then in the same version after backing up content directory manually since no other way was accessible.
 
In both cases, even after pushing old directory into /data/data/org.smssecure.smssecure, I can not get back my sms and mms. 
I also try opening app just after the end of installation, before pushing sms directory, and also closing app after installation to push sms directory before opening app.

How can I get back my sms and mms?

**Comment by FilLupin** [comment]
I currently have root access on my phone. However, Silence refuse to print my SMS. 

My priority is to import back my sms. I saved all the directory as said.

Does anyone can help my with any tips to get back SMS?

**Comment by FilLupin** [comment]
I am still looking for a way to get back my backuped SMS.
Does anyone know if this is possible?

**Comment by johanw666** [comment]
Yes, it should be technically possible (if you remember your password or if your password is easily bruteforced). However, it would require to write SQL code to revert the 0.16.3 database to a 0.15.7 database. If that does not help a program to extract the keys and decrypt the messages directly could be written. It would take a lot of time.

**Comment by FilLupin** [comment]
I remember my password but I did not saw any doc about the format used in 0.15 and 0.16 versions.
A converting tool would be a great thing to allow v0.15 users to keep their SMS and MMS when installing v0.16
